version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      groups:
          all-dependencies:
              patterns:
                  - '*'
      ignore:
          # TS7.0不被ESLint支持，禁用直到7.1发布再做打算
          - dependency-name: 'typescript'
            versions: ['>=7.0.0', '<7.1.0']

      labels:
          - 'dependencies'
      assignees:
          - 'KOSHINOawa'
