[package]
name = "webgpu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.25.2"
console_error_panic_hook = "0.1.7"
console_log = "1.1.0"
fontdue = "0.9.4"
js-sys = "0.3.104"
log = "0.4.34"
parking_lot = "0.12.5"
pollster = "1.0.1"
resvg = { version = "0.48.1", default-features = false, features = ["text", "system-fonts"] }
wasm-bindgen = { version = "0.2.127", features = ["strict-macro"] }
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = [
    "Window",
    "CssStyleDeclaration",
    "Document",
    "HtmlElement",
    "HtmlCanvasElement",
    "Gpu",
    "GpuAdapter",
    "GpuDevice",
    "GpuQueue",
    "GpuTexture",
    "GpuTextureView",
    "GpuCommandEncoder",
    "GpuRenderPassEncoder",
    "GpuRenderPipeline",
] }
wgpu = { version = "30.0.1", features = ["webgl"] }

[profile.wasm-release]
inherits = "release"
debug = 0
strip = true
lto = "fat"
opt-level = 2
panic = "abort"
codegen-units = 1
